# use docker-compose up -d to start the server with the correct settings.
version: "3.3"
services:
  monitor:
    network_mode: "host"
    image: "us-docker.pkg.dev/enfabrica-container-images/infra-prod/monitor@sha256:0247335422213e260471bf1ff92d741944014803e713fd3f1246cfbd908bf806"
    user: "nobody"
    restart: "unless-stopped"
