version: '3'

services:
  controlplane:
    image: us-docker.pkg.dev/enfabrica-container-images/infra-prod/machinist/controlplane@sha256:eee5285a2127f8409ee3cabb48f351b29b3aac5ebf1f9af1cfe5d9436a3ee137
    command:
      - "--state=/enfabrica/dns.state.json"
      - "--dns-port=4455"
      - "--bind-net=0.0.0.0"
      - "--port=4456"
      - "--domains=changeme.local"
    ports:
      - "4455:4455"
      - "4456:4456"
    volumes:
      - "/enfabrica:/enfabrica"
